---
name: cicd-demo
'on':
  push:
    branches:
      - '*'
jobs:
  build-job:
    name: Build Job
    runs-on: ubuntu-latest
    steps:
      - name: Not on Monday or Wednesday
        run: echo "Starting the build job."
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'Setup Java'
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: 'Check Java Version'
        run: |
          java --version
      - name: 'Run Tests'
        run: |
          ./gradlew test
      - name: 'Assemble JAR'
        run: |
          ./gradlew assemble
      - name: 'Get Version Number'
        run: |
          echo "VERSION=$(./gradlew properties -q | grep "version:" |
          awk '{print $2}')" >> $GITHUB_ENV
      - name: 'Publish JAR'
        uses: actions/upload-artifact@v3.1.1
        with:
          name: 'cicd-demo-${{env.VERSION}}-all.jar'
          path: build/libs/*-all.jar
      - name: 'Publish Test Report'
        if: always()
        uses: actions/upload-artifact@v2-preview
        with:
          name: 'test-report'
          path: build/reports/tests/test/*
        
